FROM jbergstroem/mariadb-alpine

ENV MYSQL_USER=PSSuser
ENV MYSQL_DATABASE=PremierServiceSolutionsDB
ENV MYSQL_PASSWORD=τнιsραssωοяδιsωεακ

ADD PSS-DB.sql /docker-entrypoint-initdb.d/PSS-DB.sql

EXPOSE 7331
